# Generated by Django 4.0.1 on 2022-01-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_filme', models.CharField(max_length=40)),
                ('imagem_font', models.TextField()),
                ('em_alta', models.BooleanField()),
                ('em_cartaz', models.BooleanField()),
            ],
        ),
    ]
