# Generated by Django 4.0.1 on 2022-01-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='nome_filme',
            field=models.CharField(max_length=255),
        ),
    ]
