# Generated by Django 4.0.1 on 2022-01-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_fanshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='atores',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='categorias',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='pais',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='produtora',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
