# Generated by Django 4.0.1 on 2022-01-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_alter_filme_nome_filme'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='principal',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
