# Generated by Django 4.0.1 on 2022-01-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_filme_principal_imagem_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='principal_imagem_font',
            field=models.TextField(null=True),
        ),
    ]
